pipeline {

    agent any

    stages {

        stage('Preparations') {
            steps {
                script{ 
                    echo 'pipeline has started'
                    
                    sh """
                         if [ ! -f helm ]; then
                            /usr/bin/curl -fsSL -o helm.tar.gz  https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
                            tar -xzf helm.tar.gz linux-amd64/helm
                            mv linux-amd64/helm helm
                            chmod +x helm
                        fi
                    """

                    sh """
                        if [ ! -f kubectl ]; then
                            /usr/bin/curl -LO "https://dl.k8s.io/release/\\$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                            chmod +x kubectl
                        fi
                    """

                    sh "kubectl get pods"
                    sh "/var/jenkins_home/workspace/Install-Hello-world-eks/helm repo add azure-samples https://azure-samples.github.io/helm-charts/"
                    sh "/var/jenkins_home/workspace/Install-Hello-world-eks/helm install hello-world azure-samples/aks-helloworld" 
                }
            }
        }
    }       
}