pipeline {

    agent any

    stages {

        stage('Preparations') {
            steps {
                script{ 
                    sh """
                       apt update & apt upgrade
                       apt install curl
                    """
                    echo 'Success'
                    // sh """
                    //      if [ ! -f helm ]; then
                    //         /usr/bin/curl -fsSL -o helm.tar.gz  https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
                    //         tar -xzf helm.tar.gz linux-amd64/helm
                    //         mv linux-amd64/helm helm
                    //     fi
                    // """
                }
            }
        }
    }       
}