pipeline {

    agent any

    stages {

        stage('Preparations') {
            steps {
                script{ 
                    sh "echo 'pipeline has started'"
                    sh "curl google.com"
                    
                    sh """
                         if [ ! -f helm ]; then
                            /usr/bin/curl -fsSL -o helm.tar.gz  https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
                            tar -xzf helm.tar.gz linux-amd64/helm
                            mv linux-amd64/helm helm
                            chmod +x helm
                        fi
                    """

                    sh "/var/jenkins_home/workspace/Install-Hello-world-eks/helm repo add azure-samples https://azure-samples.github.io/helm-charts/"
                    sh "/var/jenkins_home/workspace/Install-Hello-world-eks/helm install hello-world azure-samples/aks-helloworld" 
                }
            }
        }
    }       
}